package main

type Product struct {
	ID                 int
	Type               string
	SKU                string
	Name               string
	Published          bool
	Recommended        bool
	CatalogVisibility  string
	ShortDescription   string
	Description        string
	SalePriceDateStart string
	SalePriceDateEnd   string
	TaxStatus          string
	TaxClass           string
	InStock            bool
	Stock              int
	LowStockAmount     int
	Backorders         bool
	ManageStock        bool
	Weight             float64
	Length             float64
	Width              float64
	Height             float64
	ReviewsAllowed     bool
	PurchaseNote       string
	SalePrice          float64
	RegularPrice       float64
	Category           string
	Tags               string
	ShippingClass      string
	Image              string
	DownloadLimit      int
	DownloadExpiry     string
	Parent             int
	GroupedProducts    string
	Upsells            string
	Crosssells         string
	ExternalURL        string
	Buttontext         string
	Position           int
	Attr1Name          string
	Attr1Value         string
	Attr1Display       bool
	Attr1Global        bool
	meta1              string
	meta2              string
	meta3              string
	meta4              string
	meta5              string
	meta6              string
	meta7              string
	meta8              string
	meta9              string
	meta10             string
	meta11             string
	meta12             string
	meta13             string
	meta14             string
	meta15             string
	meta16             string
	meta17             string
	meta18             string
	meta19             string
	meta20             string
	Attr2Name          string
	Attr2Value         string
	Attr2Display       bool
	Attr2Global        bool
	Attr3Name          string
	Attr3Value         string
	Attr3Display       bool
	Attr3Global        bool
	Attr4Name          string
	Attr4Value         string
	Attr4Display       bool
	Attr4Global        bool
	Attr5Name          string
	Attr5Value         string
	Attr5Display       bool
	Attr5Global        bool
	meta21             string
	meta22             string
	meta23             string
	meta24             string
	Attr1Default       string
	meta25             string
}
